application: tournatrack
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /style
  static_dir: static
  
- url: /t\.css
  static_files: /static/t.css
  upload: /static/t\.css

- url: /reset_rooms
  script: resetrooms.app

- url: /trackpanel
  script: trackpanel.app

- url: /trackurls
  script: trackurls.app

- url: /trackgrid
  script: trackgrid.app
  
- url: /trackpin
  script: trackpin.app
  
- url: /toggle_room
  script: toggleroom.app  

- url: /del_r
  script: deleteroom.app

- url: /room
  script: room.app  

- url: /del_i
  script: deleteinst.app
  
- url: /tournaments
  script: tournaments.app
 
- url: /new_tournament
  script: newtournament.app
  
- url: /institution
  script: institution.app
  
- url: /tournament_instance
  script: tournamentinstance.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest